name: Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: "1"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python colors.py
